{% set name = "asdf" %}
{% set version = "2.14.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4e0ea64f91a4e37ed33519fe666341225b2daf21e856be6d6e5e19f52ff2be0

build:
  noarch: python
  number: 0
  entry_points:
    - asdftool = asdf.commands.main:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - pyyaml >=3.10
    - jmespath >=0.6.2
    - jsonschema >=4.0.1
    - numpy >=1.18
    - semantic_version >=2.8
    - importlib_resources >=3
    - importlib-metadata >=3
    - packaging >=16.0
    - asdf-standard >=1.0.1
    - asdf-transform-schemas >=0.2.2
    - asdf-unit-schemas >=0.1.0

test:
  requires:
    - pytest >=6.0.0
    - astropy >=5.0.4
    - gwcs
    - pytest-doctestplus
    - pytest-remotedata
    - pytest-openfiles
    - psutil
    - lz4 >=0.10
    - fsspec[http] >=2022.8.2
  imports:
    - asdf
    - asdf.commands
    - asdf.extern
    - asdf.tags
    - asdf.tags.core
  commands:
    - asdftool --help

about:
  home: http://github.com/asdf-format/asdf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python implementation of the ASDF Standard
  description: |
    Python library for reading and writing ASDF files. The Advanced Scientific
    Data Format (ASDF) is a next generation interchange format for scientific
    data.
  doc_url: http://asdf.readthedocs.io/
  dev_url: http://github.com/asdf-format/asdf

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - eslavich
    - jhunkeler
    - WilliamJamieson
    - braingram
