{% set name = "asdf" %}
{% set version = "1.3.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "05169ebb11eb90b9421851a36c2499d1c565f79a5de42d0151f7f4ddeb833d23" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - asdftool = asdf.commands.main:main
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - six >=1.9.0
  run:
    - python
    - pyyaml >=3.10
    - jsonschema >=2.3.0
    - six >=1.9.0
    - pytest >=2.7.2
    - numpy >=1.8
    - astropy >=1.3
    - semantic_version >=2.6

test:
  imports:
    - asdf
    - asdf.commands
    - asdf.extern
    - asdf.tags
    - asdf.tags.core
    - asdf.tags.fits
    - asdf.tags.time
    - asdf.tags.transform
    - asdf.tags.unit
    - asdf.tags.wcs
  commands:
    - asdftool --help

about:
  home: http://github.com/spacetelescope/asdf
  license: BSD 3-clause
  license_family: BSD
  license_file: ''
  summary: Python tools to handle ASDF files
  description: |
    Python library for reading and writing ASDF files. Advanced Scientific
    Data Format (ASDF) is a next generation interchange format for scientific
    data. asdf is an Astropy affiliated package.
  doc_url: http://asdf.readthedocs.io/
  dev_url: http://github.com/spacetelescope/asdf

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - drdavella
