travis:
  secure:
    BINSTAR_TOKEN: s2a7SHyMOeIB6B9RH4vlT6MOBb2fKEJQH9iRUJ+U9H+6AWacsmv8iNTfz4ySWTtMoonM0u08z2TJzSvmbN6cZNKpS3Uu5cCx2Xz9cwWq3A9ow+zLKabSzYn++IPrzgA6A7gtLHw17gGryuOj9+mXn9rJoKCcZD9XvkABpqvIRvtTa5MUbusx+PPn2ncjdu8+9iqBDISGVnaIsZuWxUQFAG9DI+E8YdkdtrP73DJynnGRrHFOeM4J6DxM0WhOZca6Ewcykjc4nr0yeMxM7pO4h5N5sh4EW38RikqJkQCKIuzspS6LFFNNxOf8/gTmU5nSUuV2L/YEWUrNwzmoR5Wjoi8xuHOyZ6puYZZtwdvs6jIDB5WmepKgwCURQkQc/mJo4njDcFl5mIEZcLnDFnIr6deQtc0yR7ACzWMhACjMwTZwrXR56/JEpZ51Q5d9fGatpv9NrGL3pyHw69L8bGPqG9elIl8arSSKdZj4a/p5oNNedx+tv+yXatiQr82hFiS3sqDvjWzTiW5OlnHomlX5ogNm+POBQkwRaM7zFUDFx/ckhq5h0twXzvl6SRd0kTU8hOj5JMcSPl1gAh+akkMF15V3QLLt2Ida/5y7Df/pIWgTFrxfM0lnbIqTwCDmcP5tKVg5i6SLEG1A4jiRXCBFEH68zRKl9c3sFxD5iathyKw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
