travis:
  secure:
    BINSTAR_TOKEN: FvvVIF0xZb4nxtKQ2V9B5OZmsMxiUYswWSBQ4re8+94IrNs8z4gKGtnTj/+sqxKb/yO8zLjP5BCuI9CH2cAsGxoFw/Kd8U3Mxj4is+RxHLjzCnAXfgzRAmlWOp2kDaeV48BtW3hq64bidGVQLCfl3B8UvfCSLhBbUwDjM+jxgqukWHLRJ6m95yeCTNjTXYktP08v72NNFgld+hvtkReDmPyJU2LRiO75Ieq0NW59zYN2uKwVNAlH3HjEjwNZq/UnCRESKvVGD86Zr7TdO0JRO5SiNoi5kkWBDlYm/Lw/op4FIpzudx/H3+0m5fqGtoP3LdrAa+qtLyOI9FObgXmqWcB755PFb7DqtMZlX/Z67dy7+d2GV1a7unzUdAIe9VV82HBmpHmepBlfkMq4PDMuvYuVHwCd+1yITTeUllhMjphSndwKxZS4ABDlMwZq9n993MTdkaTM2p/KkkYO9vHNh5adOEQmPplGiAli3crQ/Pp3F2f0E0vntil9UwiN9Hzw0D9ddKOSzUVxuM4a+I0TgOsa3knHmKXEuDgYsMjOhuq9Rm/9/XOr4EiDeTyWDOeJGIPi7/RCENmQtmPKvUnK3pbWY0vbeYCdIfZyLYYB6ENElVQ+YLkuWeI8Jy0LGKLWuh0wqK0Me6zOZuxzWCYpwjhjvVMvgW9ejt+L7UdJn+0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
