travis:
  secure:
    BINSTAR_TOKEN: h4aYQ5b2g94XOd5Gdx2gaeCN8syGMJdtSXWQxSkGV95zkWvob2BJZpwovbbVD7A21Sw0Qmpl6K+Ib1f2HDibwuVAU0/0QdN9O+VoYYXEULqJp3pcRbC8YcX9FqFi1MR/n1nFj+T4WOVhfHf1i0H5HyzjjeKZIepqN+iNxklanIPi69XFzaSrXSujAAieywO3DU8Wo3V7Fv1UgEfxlbXzr9DQYlbpNZgzGwiuKNZ6HcnbAoQYtWS1kg9Y7e51ic1fOjrFFDIeBFTxPigSwtd53pfLDyljtUeUEeT6jQUTiZCp5jM3Lo/WTJd3RDVjW6SfXT+VdbmEYOeDOMIwof9HDyXSUXgu5Q88j89xvrYVXuSdCF/VYJOYPlGjG9qHTOVmUhCUXN3mlv883HYZxYjNqU4bqnfTAgmFLB4nO+aclYX5ugQi4JckUTnRzGJbjmnymFWuWWfoVf47B0LSdH1aehQ+/Kd7gwiC+ramFYgeXHchEDwybx6ZMDV78U8CzpjNlIxHzYR7Re5cxaQGEAthH6kEYyn/k29JpoOqhjPXH759YgFz5PjeOXMu1GmZT02U6yM6QFpRPD4Y05IR/NCb7FhLHzNisE9ROfpaNR3HJ2HaY1DerWqknXNOtfOmVemQTd4m1jSUQSVCh7EHE0tSX7ZR9ZnZAK/0DlTWL5HA4dE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
